spring.application.name=bankonboarding
spring.data.mongodb.uri=mongodb://azhdankov_db_user:azhdankov_db_user_6jkasd@109.73.206.193:27017/azhdankov_db
logging.level.org.springframework.data.mongodb.core.MongoTemplate=debug